### ISSUE TITLE
How to use this kernel from the jupyter-console command line?

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#59] opened 2017-10-06 14:21 UTC
Is it possible to use this kernel from the jupyter-console command line repl?

I think it should be, if the implementation of the kernel is sufficiently independent from the web jupyter notebook, but when I tried this `jupyter-console --kernel="ocaml-jupyter"`, I encounter this issue:
```bash
$ jupyter-console --kernel='ocaml-jupyter'
Error: Context not closed before finalization
Error: Socket not closed before finalization
Error: Socket not closed before finalization
Error: Socket not closed before finalization
Error: Socket not closed before finalization
Error: Socket not closed before finalization
Fatal error: exception Yojson.Json_error("JupyterShellMessage.request")
Raised at file "src/core/lwt.ml", line 805, characters 16-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "src/JupyterMain.ml", line 65, characters 6-122
Re-raised at file "src/JupyterMain.ml", line 37, characters 4-64
Called from file "src/JupyterMain.ml", line 73, characters 2-9
Jupyter console 5.2.0

None


In [1]: /usr/local/lib/python2.7/dist-packages/jupyter_console/ptshell.py:617: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
In [1]: 
```
and the prompt seems to not be connected to any kernel backend.

(note that this is not so important, [utop](https://opam.ocaml.org/packages/utop/) is already a great repl for OCaml, I am mainly curious!)

**Comment by akabe** [comment] 2017-10-06 15:00
Thanks for reporting. I reproduced the bug, I have not tried jupyter-console since utop is nice as you said. I will fix this bug when I have a time.

**Comment by akabe** [comment] 2017-11-28 09:35
@Naereen I partly fixed this bug: #67. jupyter-console does not crash, but outputs non-critical warnings related to [is_complete_request](http://jupyter-client.readthedocs.io/en/latest/messaging.html#code-completeness). I think improvement of usability on jupyter-console is unnecessary due to utop.

**Comment by Naereen** [comment] 2017-11-28 10:31
Hi @akabe, thanks for having tried this.
Yes as we said, this is an extra bonus if jupyter-console works for jupyter-ocaml.

**Comment by Naereen** [comment] 2017-11-28 10:33
I'm not sure how to use opam to install from your `feature/jupyter_console` branch, so I will wait for this main branch to be updated.

**Comment by akabe** [comment] 2017-11-28 11:43
@Naereen Does this work?

```
git clone https://github.com/akabe/ocaml-jupyter -b feature/jupyter_console
cd ocaml-jupyter/
opam pin add jupyter .
```

**Comment by akabe** [comment] 2017-11-28 12:50
Maybe you need `opam remove jupyter` before `opam pin add jupyter .`

**Comment by akabe** [comment] 2017-11-28 14:34
I fixed a bug. jupyter-console currently outputs no warnings.

```console
$ git clone https://github.com/akabe/ocaml-jupyter -b feature/jupyter_console
$ cd ocaml-jupyter/
$ opam remove jupyter
$ opam pin add jupyter .
$ jupyter-console --kernel=ocaml-jupyter
Jupyter console 5.1.0

None


In [1]: let x = 1 + 5 + 9;;
Out[1]: 
val x : int = 15


In [2]: #show List.fold_left ;;
val fold_left : ('a -> 'b -> 'a) -> 'a -> 'b list -> 'a

In [3]: <Ctrl+D>
Do you really want to exit ([y]/n)? y
Shutting down kernel
```

**Comment by Naereen** [comment] 2017-11-28 15:38
Sorry, still failing...
```bash
$ opam pin add jupyter .
jupyter is now path-pinned to /tmp/ocaml-jupyter


[jupyter] /tmp/ocaml-jupyter/ synchronized
[jupyter] Installing new package description from /tmp/ocaml-jupyter

jupyter needs to be installed.
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by Naereen** [comment] 2017-11-28 15:39
But I believe you, as soon as the new feature will be shipped to master, it will be available to everybody.

**Comment by akabe** [comment] 2017-11-28 16:14
Ok. I will merge the PR after passing CI. However I worry that your error will reproduced on master... Could you try the following commands, if you have time?

opam update
opam upgrade
opam pin add jupyter . ––verbose

**Comment by akabe** [comment] 2017-11-29 04:26
Thanks for trying the fixed version. The PR is merged. This will be released at the next version.

**Closed as completed by akabe** 2017-11-29 04:26 UTC
Labels: bug
